main: net.primeux.primedropenchant.Plugin
name: PrimeDropEnchant
version: 1.0.0
author: [The PrimeUX Team, David Tkachuk (LeRoche)]
website: https://primeux.net
depend: [Vault]

commands:
  primedropenchant:
    aliases: [dropenchant, primedrop, primedropenchants]
